### ISSUE TITLE
 utils.startOfYear is not a function

### ISSUE THREAD

**Issue by PokerJava** [tarzui/date-fns-be#1]
problem  react-dom.development.js:4309 Uncaught TypeError: utils.startOfYear is not a function
<img width="539" alt="Screen Shot 2565-06-10 at 15 52 08" src="https://user-images.githubusercontent.com/26649959/173029175-78b3f2e6-a4fa-467b-855e-0eb4621ef2b5.png">

**Comment by tarzui** [comment]
Are you using date-fns-be with @mui picker ?

**Comment by tarzui** [comment]
use version 1.0.10 instead to fixed this issue @PokerJava
